import { useEffect, useMemo, useRef, useState } from 'react'
import { ancestries, callingItems, callings, classes, domainDetails, skillDetails, steps } from './data'
import { downloadSheet } from './pdf'
import { blankCharacter, downloadCharacter, loadCharacter, saveCharacter } from './storage'
import type { Character, Choice, StepId } from './types'

const stepIndex = (id: StepId) => steps.findIndex((step) => step.id === id)

function ChoiceCards({ choices, value, onChange }: { choices: Choice[]; value: string; onChange: (id: string) => void }) {
  return <div className="choice-grid">{choices.map((choice) => <button type="button" className={`choice ${value === choice.id ? 'selected' : ''}`} key={choice.id} onClick={() => onChange(choice.id)} aria-pressed={value === choice.id}>
    <span className="choice-name">{choice.name}</span><span>{choice.summary}</span><small>{choice.source}</small>
  </button>)}</div>
}

function Field({ label, value, onChange, placeholder, multiline = false, example }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; multiline?: boolean; example?: string }) {
  const props = { value, placeholder, onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(event.target.value) }
  return <label className="field"><span>{label}</span>{multiline ? <textarea {...props} rows={4} /> : <input {...props} />}{example && <details className="example"><summary>See an example</summary><p>{example}</p></details>}</label>
}

export default function App() {
  const [character, setCharacter] = useState<Character>(loadCharacter)
  const [step, setStep] = useState<StepId>('welcome')
  const [message, setMessage] = useState('Saved on this device')
  const uploadRef = useRef<HTMLInputElement>(null)
  const index = stepIndex(step)
  const patch = (changes: Partial<Character>) => setCharacter((current) => ({ ...current, ...changes }))
  useEffect(() => { saveCharacter(character); setMessage('Saved on this device') }, [character])
  const selected = <T extends Choice>(all: T[], value: string) => all.find((item) => item.id === value)
  const required = useMemo(() => [character.name, character.ancestry, character.calling, character.characterClass].filter(Boolean).length, [character])
  const selectedClass = selected(classes, character.characterClass)
  const setClass = (characterClass: string) => {
    const choice = selected(classes, characterClass)
    if (!choice) return
    const selectedCoreAbilities = choice.coreAbilities.map((core) => core.id)
    patch({ characterClass, selectedCoreAbilities, coreAbility: choice.coreAbilities.map((core) => `${core.name}: ${core.description}`).join('\n\n'), skills: choice.starter.skills, domains: choice.starter.domains, equipment: choice.starter.equipment[0], resources: choice.starter.resource, protections: choice.starter.protectionNote, skillKnacks: {}, domainKnacks: {} })
  }
  const toggleCoreAbility = (id: string) => {
    if (!selectedClass) return
    const selectedCoreAbilities = character.selectedCoreAbilities.includes(id) ? character.selectedCoreAbilities.filter((value) => value !== id) : [...character.selectedCoreAbilities, id]
    patch({ selectedCoreAbilities, coreAbility: selectedClass.coreAbilities.filter((core) => selectedCoreAbilities.includes(core.id)).map((core) => `${core.name}: ${core.description}`).join('\n\n') })
  }
  const importCharacter = (file?: File) => {
    if (!file) return
    const reader = new FileReader()
    reader.onload = () => { try { const imported = JSON.parse(String(reader.result)); if (imported.version !== 1) throw new Error(); setCharacter({ ...blankCharacter(), ...imported }); setMessage('Backup restored') } catch { setMessage('That backup could not be read') } }
    reader.readAsText(file)
  }
  const next = () => setStep(steps[Math.min(index + 1, steps.length - 1)].id)
  const previous = () => setStep(steps[Math.max(index - 1, 0)].id)

  return <main>
    <header className="masthead"><a href="#top" className="brand">HEART <i>Character Creator</i></a><span className="save-status">{message}</span></header>
    <div className="shell" id="top">
      <aside><p className="eyebrow">Your descent</p><ol>{steps.map((item, itemIndex) => <li key={item.id}><button type="button" className={step === item.id ? 'active' : ''} onClick={() => setStep(item.id)}><b>{String(itemIndex + 1).padStart(2, '0')}</b>{item.label}</button></li>)}</ol>
      <div className="utility"><button type="button" onClick={() => downloadCharacter(character)}>Download backup</button><button type="button" onClick={() => uploadRef.current?.click()}>Restore backup</button><button type="button" className="quiet" onClick={() => { setCharacter(blankCharacter()); setStep('welcome'); setMessage('Started a fresh character') }}>Start over</button><input hidden type="file" accept="application/json" ref={uploadRef} onChange={(event) => importCharacter(event.target.files?.[0])} /></div></aside>
      <section className="journey"><p className="eyebrow">{steps[index].kicker}</p>
        {step === 'welcome' && <><h1>A character is a promise you make to the Heart.</h1><p className="lede">This is a companion for building a core-book Heart character. It keeps your choices on this device and helps you prepare a sheet to take to your table.</p><div className="notice"><b>Bring the book.</b> This tool uses short original prompts, not the game’s full rules. Keep the official Heart materials nearby for exact abilities, equipment, and advancement details.</div><div className="welcome-actions"><button className="primary" onClick={next}>Create a character</button><a href="https://rowanrookanddecard.com/product/heart-the-city-beneath-rpg/" target="_blank" rel="noreferrer">Find the official game</a></div></>}
        {step === 'identity' && <><h1>Start with the person, not the numbers.</h1><p className="lede">A name can be provisional. What matters is an image you can play toward.</p><div className="fields two"><Field label="Character name" value={character.name} onChange={(name) => patch({ name })} placeholder="What are you called?" example="Mara Vell, the name you kept after abandoning your old life." /><Field label="Pronouns (optional)" value={character.pronouns} onChange={(pronouns) => patch({ pronouns })} placeholder="she/her, they/them..." /></div><Field label="A first impression" value={character.appearance} onChange={(appearance) => patch({ appearance })} placeholder="What do the others notice first?" multiline example="A rain-soaked cavalry coat, a cracked brass mask, and hands that never stop shaking." /></>}
        {step === 'ancestry' && <><h1>Choose an ancestry that gives you good questions.</h1><p className="lede">There are no mechanical differences here. Pick the history and perspective you want to explore.</p><ChoiceCards choices={ancestries} value={character.ancestry} onChange={(ancestry) => patch({ ancestry })} /><Field label="What part of this heritage matters most to you?" value={character.ancestryPrompt} onChange={(ancestryPrompt) => patch({ ancestryPrompt })} placeholder="A memory, tradition, scar, or expectation..." multiline example="Your family still calls you by a title you can no longer bear." /><div className="fields two"><Field label="Keepsake one" value={character.keepsakes[0]} onChange={(value) => patch({ keepsakes: [value, character.keepsakes[1]] })} placeholder="Something small you carried below" example="A key to an apartment that no longer exists." /><Field label="Keepsake two" value={character.keepsakes[1]} onChange={(value) => patch({ keepsakes: [character.keepsakes[0], value] })} placeholder="Something you cannot leave behind" example="A pressed flower from the last bright garden you saw." /></div></>}
        {step === 'calling' && <><h1>Your calling is the reason you risk the descent.</h1><p className="lede">Choose the pressure that will make difficult decisions feel charged rather than arbitrary.</p><ChoiceCards choices={callings} value={character.calling} onChange={(calling) => patch({ calling, callingItem: '' })} /><Field label="Make it personal" value={character.callingPrompt} onChange={(callingPrompt) => patch({ callingPrompt })} placeholder="Who, what, or where makes this calling impossible to ignore?" multiline example="Your younger sister vanished into a train station that does not exist on any map." /><label className="field"><span>Calling item</span><select value={character.callingItem} disabled={!character.calling} onChange={(event) => patch({ callingItem: event.target.value })}><option value="">{character.calling ? 'Choose your calling item' : 'Choose a calling first'}</option>{(callingItems[character.calling] ?? []).map((item) => <option value={item} key={item}>{item}</option>)}</select><small>These ten choices come from the selected calling’s core-book table.</small></label><div className="fields two"><Field label="Active beat one" value={character.activeBeats[0]} onChange={(value) => patch({ activeBeats: [value, character.activeBeats[1]] })} placeholder="A goal worth risking something for" example="Get the map into the hands of a person who can read it." /><Field label="Active beat two" value={character.activeBeats[1]} onChange={(value) => patch({ activeBeats: [character.activeBeats[0], value] })} placeholder="Another promise to the story" example="Find out whether the voice in your dreams belongs to your mother." /></div></>}
        {step === 'class' && <><h1>Pick the kind of trouble you are good at.</h1><p className="lede">Your class now sets the legal starting skill, domain, resource, equipment choices, and core abilities for this character.</p><ChoiceCards choices={classes} value={character.characterClass} onChange={setClass} /></>}
        {step === 'abilities' && <><h1>Understand what your class gives you.</h1><p className="lede">Core abilities are granted by your class. Keep the ones you want printed on the sheet selected; their full reminders are included below.</p>{selectedClass ? <div className="ability-list">{selectedClass.coreAbilities.map((core) => <label className="ability-card" key={core.id}><input type="checkbox" checked={character.selectedCoreAbilities.includes(core.id)} onChange={() => toggleCoreAbility(core.id)} /><span><b>{core.name}</b><p>{core.description}</p></span></label>)}<Field label="Additional ability notes" value={character.abilities} onChange={(abilities) => patch({ abilities })} placeholder="A short reminder about an ability, advance, or rule your table wants handy" multiline example="When I enter my true form, describe the moth wings unfolding from beneath my coat." /></div> : <div className="notice">Choose a class first; its core abilities will appear here.</div>}</>}
        {step === 'build' && <><h1>Your class determines your starting kit.</h1><p className="lede">Skills and domains below are locked to the class you chose. Equipment and resource options are taken from that class’s Core Traits.</p>{selectedClass ? <><div className="selection-columns"><div><h2>Starting skill</h2>{selectedClass.starter.skills.map((skill) => <div className="reference-card" key={skill}><b>{skill}</b><p>{skillDetails[skill]}</p><Field label={`${skill} knack (optional)`} value={character.skillKnacks[skill] ?? ''} onChange={(value) => patch({ skillKnacks: { ...character.skillKnacks, [skill]: value } })} placeholder="A defining specialty" example="Tracking by scent through crowded stations." /></div>)}</div><div><h2>Starting domain</h2>{selectedClass.starter.domains.map((domain) => <div className="reference-card" key={domain}><b>{domain}</b><p>{domainDetails[domain]}</p><Field label={`${domain} knack (optional)`} value={character.domainKnacks[domain] ?? ''} onChange={(value) => patch({ domainKnacks: { ...character.domainKnacks, [domain]: value } })} placeholder="A defining connection" example="You know which abandoned tunnels still have air." /></div>)}</div></div><label className="field"><span>Equipment loadout</span><select value={character.equipment} onChange={(event) => patch({ equipment: event.target.value })}>{selectedClass.starter.equipment.map((item) => <option value={item} key={item}>{item}</option>)}</select><small>Only the loadouts granted by {selectedClass.name} are available.</small></label><div className="fields two"><Field label="Starting resource" value={character.resources} onChange={(resources) => patch({ resources })} placeholder="Class resource" multiline /><Field label="Protection rules" value={character.protections} onChange={(protections) => patch({ protections })} placeholder="Class protection rule" multiline /></div></> : <div className="notice">Choose a class before selecting equipment, resources, and protections.</div>}</>}
        {step === 'story' && <><h1>Leave room for the parts that matter most.</h1><p className="lede">A few concrete connections will give your group material to play with on the first session.</p><div className="fields two"><Field label="History" value={character.history} onChange={(history) => patch({ history })} placeholder="What brought you here?" multiline /><Field label="Relationships" value={character.relationships} onChange={(relationships) => patch({ relationships })} placeholder="Who do you owe, miss, or fear?" multiline /><Field label="Bonds" value={character.bonds} onChange={(bonds) => patch({ bonds })} placeholder="What connects you to the other characters?" multiline /><Field label="Notes" value={character.notes} onChange={(notes) => patch({ notes })} placeholder="Loose ends, questions, and details to remember" multiline /></div></>}
        {step === 'review' && <><h1>{required === 4 ? 'You are ready to go below.' : 'A few foundations are still missing.'}</h1><p className="lede">You have completed {required} of 4 essential choices: name, ancestry, calling, and class. You can always return to any step before printing.</p><div className="review"><div><span>Name</span><b>{character.name || 'Not yet chosen'}</b></div><div><span>Ancestry</span><b>{selected(ancestries, character.ancestry)?.name || 'Not yet chosen'}</b></div><div><span>Calling</span><b>{selected(callings, character.calling)?.name || 'Not yet chosen'}</b></div><div><span>Class</span><b>{selected(classes, character.characterClass)?.name || 'Not yet chosen'}</b></div></div><div className="notice"><b>Before you print:</b> confirm class-granted skills, domains, equipment, protections, and full ability text against the official core book. The sheet leaves stress trackers blank for play.</div><button className="primary export" disabled={required < 4} onClick={() => downloadSheet(character).catch(() => setMessage('Could not create PDF - please try again'))}>Download character sheet PDF</button></>}
        {step !== 'welcome' && <nav className="controls"><button type="button" onClick={previous}>Back</button>{step !== 'review' && <button type="button" className="primary" onClick={next}>Continue</button>}</nav>}
      </section>
    </div>
    <footer>Heart: The City Beneath is published by Rowan, Rook and Decard. This unofficial companion is not affiliated with or endorsed by the publisher.</footer>
  </main>
}
