import { useEffect, useMemo, useRef, useState } from 'react'
import { ancestries, callings, classes, domains, skills, steps } from './data'
import { downloadSheet } from './pdf'
import { blankCharacter, downloadCharacter, loadCharacter, saveCharacter } from './storage'
import type { Character, Choice, StepId } from './types'

const stepIndex = (id: StepId) => steps.findIndex((step) => step.id === id)

function ChoiceCards({ choices, value, onChange }: { choices: Choice[]; value: string; onChange: (id: string) => void }) {
  return <div className="choice-grid">{choices.map((choice) => <button type="button" className={`choice ${value === choice.id ? 'selected' : ''}`} key={choice.id} onClick={() => onChange(choice.id)} aria-pressed={value === choice.id}>
    <span className="choice-name">{choice.name}</span><span>{choice.summary}</span><small>{choice.source}</small>
  </button>)}</div>
}

function Field({ label, value, onChange, placeholder, multiline = false }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; multiline?: boolean }) {
  const props = { value, placeholder, onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(event.target.value) }
  return <label className="field"><span>{label}</span>{multiline ? <textarea {...props} rows={4} /> : <input {...props} />}</label>
}

export default function App() {
  const [character, setCharacter] = useState<Character>(loadCharacter)
  const [step, setStep] = useState<StepId>('welcome')
  const [message, setMessage] = useState('Saved on this device')
  const uploadRef = useRef<HTMLInputElement>(null)
  const index = stepIndex(step)
  const patch = (changes: Partial<Character>) => setCharacter((current) => ({ ...current, ...changes }))
  useEffect(() => { saveCharacter(character); setMessage('Saved on this device') }, [character])
  const selected = (all: Choice[], value: string) => all.find((item) => item.id === value)
  const required = useMemo(() => [character.name, character.ancestry, character.calling, character.characterClass].filter(Boolean).length, [character])
  const toggle = (field: 'skills' | 'domains', item: string) => patch({ [field]: character[field].includes(item) ? character[field].filter((value) => value !== item) : [...character[field], item] })
  const importCharacter = (file?: File) => {
    if (!file) return
    const reader = new FileReader()
    reader.onload = () => { try { const imported = JSON.parse(String(reader.result)); if (imported.version !== 1) throw new Error(); setCharacter({ ...blankCharacter(), ...imported }); setMessage('Backup restored') } catch { setMessage('That backup could not be read') } }
    reader.readAsText(file)
  }
  const next = () => setStep(steps[Math.min(index + 1, steps.length - 1)].id)
  const previous = () => setStep(steps[Math.max(index - 1, 0)].id)

  return <main>
    <header className="masthead"><a href="#top" className="brand">HEART <i>Character Creator</i></a><span className="save-status">{message}</span></header>
    <div className="shell" id="top">
      <aside><p className="eyebrow">Your descent</p><ol>{steps.map((item, itemIndex) => <li key={item.id}><button type="button" className={step === item.id ? 'active' : ''} onClick={() => setStep(item.id)}><b>{String(itemIndex + 1).padStart(2, '0')}</b>{item.label}</button></li>)}</ol>
      <div className="utility"><button type="button" onClick={() => downloadCharacter(character)}>Download backup</button><button type="button" onClick={() => uploadRef.current?.click()}>Restore backup</button><button type="button" className="quiet" onClick={() => { setCharacter(blankCharacter()); setStep('welcome'); setMessage('Started a fresh character') }}>Start over</button><input hidden type="file" accept="application/json" ref={uploadRef} onChange={(event) => importCharacter(event.target.files?.[0])} /></div></aside>
      <section className="journey"><p className="eyebrow">{steps[index].kicker}</p>
        {step === 'welcome' && <><h1>A character is a promise you make to the Heart.</h1><p className="lede">This is a companion for building a core-book Heart character. It keeps your choices on this device and helps you prepare a sheet to take to your table.</p><div className="notice"><b>Bring the book.</b> This tool uses short original prompts, not the game’s full rules. Keep the official Heart materials nearby for exact abilities, equipment, and advancement details.</div><div className="welcome-actions"><button className="primary" onClick={next}>Create a character</button><a href="https://rowanrookanddecard.com/product/heart-the-city-beneath-rpg/" target="_blank" rel="noreferrer">Find the official game</a></div></>}
        {step === 'identity' && <><h1>Start with the person, not the numbers.</h1><p className="lede">A name can be provisional. What matters is an image you can play toward.</p><div className="fields two"><Field label="Character name" value={character.name} onChange={(name) => patch({ name })} placeholder="What are you called?" /><Field label="Pronouns (optional)" value={character.pronouns} onChange={(pronouns) => patch({ pronouns })} placeholder="she/her, they/them..." /></div><Field label="A first impression" value={character.appearance} onChange={(appearance) => patch({ appearance })} placeholder="What do the others notice first?" multiline /></>}
        {step === 'ancestry' && <><h1>Choose an ancestry that gives you good questions.</h1><p className="lede">There are no mechanical differences here. Pick the history and perspective you want to explore.</p><ChoiceCards choices={ancestries} value={character.ancestry} onChange={(ancestry) => patch({ ancestry })} /><Field label="What part of this heritage matters most to you?" value={character.ancestryPrompt} onChange={(ancestryPrompt) => patch({ ancestryPrompt })} placeholder="A memory, tradition, scar, or expectation..." multiline /><div className="fields two"><Field label="Keepsake one" value={character.keepsakes[0]} onChange={(value) => patch({ keepsakes: [value, character.keepsakes[1]] })} placeholder="Something small you carried below" /><Field label="Keepsake two" value={character.keepsakes[1]} onChange={(value) => patch({ keepsakes: [character.keepsakes[0], value] })} placeholder="Something you cannot leave behind" /></div></>}
        {step === 'calling' && <><h1>Your calling is the reason you risk the descent.</h1><p className="lede">Choose the pressure that will make difficult decisions feel charged rather than arbitrary.</p><ChoiceCards choices={callings} value={character.calling} onChange={(calling) => patch({ calling })} /><Field label="Make it personal" value={character.callingPrompt} onChange={(callingPrompt) => patch({ callingPrompt })} placeholder="Who, what, or where makes this calling impossible to ignore?" multiline /><Field label="Calling item" value={character.callingItem} onChange={(callingItem) => patch({ callingItem })} placeholder="Check your book for the option you choose" /><div className="fields two"><Field label="Active beat one" value={character.activeBeats[0]} onChange={(value) => patch({ activeBeats: [value, character.activeBeats[1]] })} placeholder="A goal worth risking something for" /><Field label="Active beat two" value={character.activeBeats[1]} onChange={(value) => patch({ activeBeats: [character.activeBeats[0], value] })} placeholder="Another promise to the story" /></div></>}
        {step === 'class' && <><h1>Pick the kind of trouble you are good at.</h1><p className="lede">A class gives your character a distinctive approach to surviving the City Beneath. Read the full class entry in the core book before finalizing abilities.</p><ChoiceCards choices={classes} value={character.characterClass} onChange={(characterClass) => patch({ characterClass })} /><Field label="Core ability" value={character.coreAbility} onChange={(coreAbility) => patch({ coreAbility })} placeholder="Write the name and a brief reminder from your book" /><Field label="Why does this class fit your character?" value={character.abilities} onChange={(abilities) => patch({ abilities })} placeholder="What does this power cost, protect, or reveal?" multiline /></>}
        {step === 'build' && <><h1>Give yourself tools, not a shopping list.</h1><p className="lede">Select the skills and domains granted by your class and record their exact details from the rulebook.</p><div className="selection-columns"><div><h2>Skills</h2>{skills.map((skill) => <label className="check" key={skill}><input type="checkbox" checked={character.skills.includes(skill)} onChange={() => toggle('skills', skill)} /><span>{skill}</span>{character.skills.includes(skill) && <input aria-label={`${skill} knack`} value={character.skillKnacks[skill] ?? ''} onChange={(event) => patch({ skillKnacks: { ...character.skillKnacks, [skill]: event.target.value } })} placeholder="Knack (optional)" />}</label>)}</div><div><h2>Domains</h2>{domains.map((domain) => <label className="check" key={domain}><input type="checkbox" checked={character.domains.includes(domain)} onChange={() => toggle('domains', domain)} /><span>{domain}</span>{character.domains.includes(domain) && <input aria-label={`${domain} knack`} value={character.domainKnacks[domain] ?? ''} onChange={(event) => patch({ domainKnacks: { ...character.domainKnacks, [domain]: event.target.value } })} placeholder="Knack (optional)" />}</label>)}</div></div><Field label="Protections" value={character.protections} onChange={(protections) => patch({ protections })} placeholder="Record your protection names and values" multiline /><div className="fields two"><Field label="Equipment" value={character.equipment} onChange={(equipment) => patch({ equipment })} placeholder="What you carry" multiline /><Field label="Resources" value={character.resources} onChange={(resources) => patch({ resources })} placeholder="People, places, or assets you can call on" multiline /></div></>}
        {step === 'story' && <><h1>Leave room for the parts that matter most.</h1><p className="lede">A few concrete connections will give your group material to play with on the first session.</p><div className="fields two"><Field label="History" value={character.history} onChange={(history) => patch({ history })} placeholder="What brought you here?" multiline /><Field label="Relationships" value={character.relationships} onChange={(relationships) => patch({ relationships })} placeholder="Who do you owe, miss, or fear?" multiline /><Field label="Bonds" value={character.bonds} onChange={(bonds) => patch({ bonds })} placeholder="What connects you to the other characters?" multiline /><Field label="Notes" value={character.notes} onChange={(notes) => patch({ notes })} placeholder="Loose ends, questions, and details to remember" multiline /></div></>}
        {step === 'review' && <><h1>{required === 4 ? 'You are ready to go below.' : 'A few foundations are still missing.'}</h1><p className="lede">You have completed {required} of 4 essential choices: name, ancestry, calling, and class. You can always return to any step before printing.</p><div className="review"><div><span>Name</span><b>{character.name || 'Not yet chosen'}</b></div><div><span>Ancestry</span><b>{selected(ancestries, character.ancestry)?.name || 'Not yet chosen'}</b></div><div><span>Calling</span><b>{selected(callings, character.calling)?.name || 'Not yet chosen'}</b></div><div><span>Class</span><b>{selected(classes, character.characterClass)?.name || 'Not yet chosen'}</b></div></div><div className="notice"><b>Before you print:</b> confirm class-granted skills, domains, equipment, protections, and full ability text against the official core book. The sheet leaves stress trackers blank for play.</div><button className="primary export" disabled={required < 4} onClick={() => downloadSheet(character).catch(() => setMessage('Could not create PDF - please try again'))}>Download character sheet PDF</button></>}
        {step !== 'welcome' && <nav className="controls"><button type="button" onClick={previous}>Back</button>{step !== 'review' && <button type="button" className="primary" onClick={next}>Continue</button>}</nav>}
      </section>
    </div>
    <footer>Heart: The City Beneath is published by Rowan, Rook and Decard. This unofficial companion is not affiliated with or endorsed by the publisher.</footer>
  </main>
}
