import type { Choice, ClassChoice, StepId } from './types'

export const steps: { id: StepId; label: string; kicker: string }[] = [
  { id: 'welcome', label: 'Begin', kicker: 'Before you delve' },
  { id: 'identity', label: 'Identity', kicker: 'Who are you?' },
  { id: 'ancestry', label: 'Ancestry', kicker: 'Where did you begin?' },
  { id: 'calling', label: 'Calling', kicker: 'Why do you keep going?' },
  { id: 'class', label: 'Class', kicker: 'How do you survive?' },
  { id: 'abilities', label: 'Abilities', kicker: 'What can you do?' },
  { id: 'build', label: 'Loadout', kicker: 'What do you bring?' },
  { id: 'story', label: 'Story', kicker: 'What matters to you?' },
  { id: 'review', label: 'Finish', kicker: 'Ready to descend' },
]

export const ancestries: Choice[] = [
  { id: 'drow', name: 'Drow', summary: 'A survivor shaped by the impossible city above and the roads beneath it. Choose details that make your relationship with Spire feel personal.', source: 'Heart core book, character creation: ancestry' },
  { id: 'human', name: 'Human', summary: 'Grounded, adaptable, and never uncomplicated. Decide what brought you to the City Beneath and what you are still trying to prove.', source: 'Heart core book, character creation: ancestry' },
  { id: 'aelfir', name: 'Aelfir', summary: 'Beautiful, long-lived, and deeply out of place. Consider what status or certainty you have lost - or what you hope the depths will erase.', source: 'Heart core book, character creation: ancestry' },
  { id: 'gnoll', name: 'Gnoll', summary: 'A person of fierce communities, memory, and appetite. Think about the people you carry with you, whether they are present or not.', source: 'Heart core book, character creation: ancestry' },
]

export const callings: Choice[] = [
  { id: 'adventure', name: 'Adventure', summary: 'You want the story, the danger, and the thing no sensible person would pursue. Give your hunger for discovery a face.', source: 'Heart core book, callings' },
  { id: 'enlightenment', name: 'Enlightenment', summary: 'You believe the depths hold a truth worth the cost. Name the question that keeps pulling you farther down.', source: 'Heart core book, callings' },
  { id: 'forced', name: 'Forced', summary: 'You did not choose this road freely. Decide who or what has made the descent unavoidable.', source: 'Heart core book, callings' },
  { id: 'heartsong', name: 'Heartsong', summary: 'Something in the Heart calls to you in a voice only you can hear. Describe the promise it seems to make.', source: 'Heart core book, callings' },
  { id: 'penitent', name: 'Penitent', summary: 'You came below to answer for something. Decide whether you seek forgiveness, punishment, or a way to make amends.', source: 'Heart core book, callings' },
]

export const callingItems: Record<string, string[]> = {
  adventure: ['Pulp novel loosely based on your exploits', 'Mouth organ', 'Spider silk scarf in a dashing colour', 'Inaccurate map of the Heart bought in Derelictus', 'Copy of RAVENOUS SHE-WITCHES OF HALLOW', 'Paper and sketching charcoal', 'Fake abomination-hunting license', 'Unpunched Vermissian ticket used as a good-luck charm', 'Letters from your mum asking when you are coming home', 'Expensive kohl eyeliner and pocket mirror'],
  enlightenment: ['Set of fragile magnifying lenses', 'Book of handwritten theories and observations', 'Portable alchemy kit in a leather box', 'Dried dream-mushrooms', 'Incense sticks that burn dirty-blue smoke', 'Red-string-and-pins collage of the people who tried to stop you', 'List of people who are Going To Pay', 'Bag of heavy glass fortune stones', 'Taxidermied owl', 'Imported book of meditative stances and spirit-cleansing recipes'],
  forced: ['Daguerreotype of your son', 'Moonsilver collar', 'Signed contract detailing your employment', 'Matchbook from The Manticore casino', 'Subjugation sliver implanted in your neck', 'Guild brand on your upper arm', 'Deed to an apartment in Ivory Row', 'Mark where your soul used to be', 'Your master’s iron sigil', 'Codebook for making reports'],
  heartsong: ['Ink-blotted dream journal with maps', 'Bag of bitter stimulant pastilles', 'Steel syringe and opiate powder', 'The word THEOLOSIAN growing over your chest', 'Barely-viable homunculus', 'Twenty sketches of a man you are convinced you will meet', 'Signed copy of BEYOND THE EDGE OF MADNESS', 'Mandala made from hollow crowbones', 'Impressionist votive image of a Witch', 'Greenish candles for dreamless sleep'],
  penitent: ['Absolution chains', 'Vellum scroll bearing a record of your crimes', 'Still-itching tattoo depicting your sins', 'The skull of someone you loved', 'Vial of ashes with a name on it', 'Masonry fragment from a destroyed statue', 'Book of handwritten melodramatic poetry', 'Locket depicting a beautiful one-eyed drow', 'Ceremonial bronze Watchful Eye', 'Brand identifying you as a knight of the Covenant of the Fallen Tower'],
}

const ability = (id: string, name: string, description: string) => ({ id, name, description })

export const classes: ClassChoice[] = [
  { id: 'cleaver', name: 'Cleaver', summary: 'A fighter who meets horror head-on. Choose this if you want your character’s violence to feel direct, costly, and personal.', source: 'Heart core book, pp. 26-30', coreAbilities: [ability('heartsblood', 'Heartsblood', 'Your minimum protection for every resistance equals the Heart tier you currently occupy.'), ability('red-feast', 'The Red Feast', 'When you consume a resource, you temporarily gain its domains; an existing domain becomes a fitting knack.')], starter: { skills: ['Hunt'], domains: ['Cursed'], resource: 'Freshly harvested heart that still occasionally twitches - D6 Wild', equipment: ['Hunting knife (Kill D6) + Cleaver (Kill D8, Brutal, Tiring)', 'Hunting knife (Kill D6) + bone charms and animal-gut sutures (Mend Blood D6)', 'Hunting knife (Kill D6) + heavy-draw bow (Kill D8, Ranged, Tiring)'], protectionNote: 'Heartsblood sets a tier-based minimum protection for every resistance.' } },
  { id: 'deadwalker', name: 'Deadwalker', summary: 'Someone who has crossed close to death and learned to travel with it. Choose this for ghostly ties and an intimate relationship with endings.', source: 'Heart core book, pp. 31-35', coreAbilities: [ability('death-follows-close', 'Death Follows Close', 'Your visible-to-you death protects you the first time each session you suffer Major Blood, Mind, or Fortune fallout.'), ability('enter-the-grey', 'Enter the Grey', 'A Delve + Religion ritual lets you and companions step into the Grey, the shadow of the living world.')], starter: { skills: ['Delve'], domains: ['Desolate'], resource: 'Bag of interesting teeth - D6 Desolate', equipment: ['Hunting rifle (Kill D6, Extreme Range, Reload)', 'Greatsword (Kill D10, Tiring)', 'Bootleg ambrosia (Mend Mind D6, Potent, Expensive) + ritual blade (Kill D6)'], protectionNote: 'No starting protection is granted by the class traits.' } },
  { id: 'deep-apiarist', name: 'Deep Apiarist', summary: 'A keeper of strange bees and stranger symbioses. Choose this for body horror, care, and a living colony at your side.', source: 'Heart core book, pp. 36-40', coreAbilities: [ability('the-hive', 'The Hive', 'The sweetlings inside you clear all Mind stress at the start of each situation; you cannot benefit from Mind protection or remove Mind stress otherwise.'), ability('release-the-swarm', 'Release the Swarm', 'You can send a defensive swarm that acts as a Kill D4, Spread, Ranged weapon.')], starter: { skills: ['Mend'], domains: ['Occult'], resource: 'Heartsbloom rose in a glass jar - D6 Occult, Fragile', equipment: ['Hive tool (Kill D4, Brutal) + dimensional barometer (Delve D6)', 'Hive tool (Kill D4, Brutal) + hunting rifle (Kill D6, Reload, Extreme Range)', 'Hive tool (Kill D4, Brutal) + smoker (Kill D4, Debilitating, Smoke)'], protectionNote: 'The Hive prevents Mind protection; use other resistance protections normally.' } },
  { id: 'heretic', name: 'Heretic', summary: 'A believer whose faith does not fit safely in the world. Choose this to wrestle with devotion, miracles, and dangerous certainty.', source: 'Heart core book, pp. 41-45', coreAbilities: [ability('ministrations', 'Ministrations', 'Once per session, lead allies in praise to remove Minor Blood or Mind fallout, or downgrade Major fallout; doing so on a delve adds D4 resistance.')], starter: { skills: ['Mend'], domains: ['Religion'], resource: 'Single devotional candle with a silver flame - D6 Religion', equipment: ['Spireblack brazier (unlit Kill D6; lit Kill D8, Obscuring, Dangerous)', 'Breech-loading pistol (Kill D6, Ranged, Reload) + Seeker’s blade (Kill D6, Brutal)', 'Scripture-etched bandages and blessed oils (Mend Blood/Mind D6) + staff (Kill D6)'], protectionNote: 'No starting protection is granted by the class traits.' } },
  { id: 'hound', name: 'Hound', summary: 'A tracker who follows people, monsters, and unfinished business. Choose this for pursuit, isolation, and relentless competence.', source: 'Heart core book, pp. 46-50', coreAbilities: [ability('in-the-thick-of-it', 'In the Thick of It', 'Once per situation, stress that would hit another resistance can be marked to Fortune instead; Fortune fallout gives mastery for the situation.')], starter: { skills: ['Hunt'], domains: ['Haven'], resource: 'Bottle of rotgut liquor - D6 Haven', equipment: ['Standard-issue Legrande rifle (Kill D8, Ranged, Piercing, Expensive)', 'Repeater sidearm (Kill D6, Ranged, Brutal, Reload) + knife (Kill D6)', 'Well-stocked haversack (Mend Supplies D6) + cudgel (Kill D6)'], protectionNote: 'No starting protection is granted by the class traits.' } },
  { id: 'incarnadine', name: 'Incarnadine', summary: 'A person remade by the Heart’s impossible beauty. Choose this for transformation, desire, and power that changes what you are.', source: 'Heart core book, pp. 51-55', coreAbilities: [ability('cost-of-doing-business', 'The Cost of Doing Business', 'Consume a resource, set aside its die, then replace an unrolled die in a later action or stress roll with it; an unused die becomes Fortune stress.'), ability('mutually-assured-destruction', 'Mutually Assured Destruction', 'If you die, your soul wards explode and inflict D8 plus current Fortune stress on those nearby.')], starter: { skills: ['Compel'], domains: ['Haven'], resource: 'Second-hand wedding ring - D6 Haven', equipment: ['Hooked blade (Kill D6) + filigreed revolver (Kill D8, Ranged, Expensive)', 'Hooked blade (Kill D6) + Bailiff’s iron cudgel (Kill D8, Tiring)', 'Hooked blade (Kill D6) + home-made Spireblack pipe bombs (Kill D6, Ranged, Spread, One-Shot)'], protectionNote: 'No starting protection is granted by the class traits.' } },
  { id: 'junk-mage', name: 'Junk Mage', summary: 'A scavenger-mystic who finds magic in discarded things. Choose this for inventive problem-solving and wonderfully unreliable rituals.', source: 'Heart core book, pp. 56-60', coreAbilities: [ability('ravening-knowledge', 'Ravening Knowledge', 'When your Mind stress is 4 or higher, you roll with mastery when casting a class spell.'), ability('sacrifice', 'Sacrifice', 'Before casting a class spell, destroy an Occult resource and add its roll to protection against stress from that spell.')], starter: { skills: ['Discern'], domains: ['Occult'], resource: 'Vial of cursed ink - D6 Occult', equipment: ['Two old-fashioned pistols (Kill D8, Ranged, Loud, One-Shot)', 'Hungry knife (Kill D6, Brutal, Bloodbound, Dangerous)', 'Overstuffed coat (Mend Supplies D6) + blunderbuss (Kill D4, Spread, Point-blank, One-shot)'], protectionNote: 'Sacrifice provides temporary protection when you destroy a qualifying Occult resource.' } },
  { id: 'vermissian-knight', name: 'Vermissian Knight', summary: 'A veteran of the cursed underground railway. Choose this for martial discipline, old routes, and loyalty to a lost institution.', source: 'Heart core book, pp. 61-65', coreAbilities: [ability('vermissian-plate', 'Vermissian Plate', 'Once per session, consume a Technology or Occult resource to repair or augment your armour for healing, harm, temporary access, or Blood protection.')], starter: { skills: ['Delve'], domains: ['Technology'], resource: 'Spare capacitors and wires - D6 Technology', equipment: ['Pneumatic hammer (Kill D8, Brutal, Loud, Tiring)', 'Scrap sword (Kill D6) + Magelight rig (Delve D6)', 'Steel door shield (Kill D6, Block)'], protectionNote: 'Vermissian Plate can provide temporary Blood protection with a D8+ qualifying resource.' } },
  { id: 'witch', name: 'Witch', summary: 'A practitioner of intimate, unsettling magic. Choose this for bargains, secrets, and power that is never emotionally neutral.', source: 'Heart core book, pp. 66-70', coreAbilities: [ability('crucible', 'Crucible', 'Roll D6 against current Echo stress: on a low roll clear Echo and gain mastery on your next action; on a high roll take Echo stress.'), ability('true-form', 'True Form', 'Enter a heartsblooded form at will or after Major fallout: gain mastery on Hunt and Kill, while other checks become Risky until the situation ends.')], starter: { skills: ['Compel'], domains: ['Occult'], resource: 'Tattered finery - D6 Haven', equipment: ['Sacred blade (Kill D6, Bloodbound)', 'Goat’s Leg carbine (Kill D6, Ranged, Reload)', 'Physiker’s bag (Mend Blood D6)'], protectionNote: 'No starting protection is granted by the class traits.' } },
]

export const skillDetails: Record<string, string> = { Compel: 'Influence, deceive, or force someone to do what you need.', Delve: 'Navigate, explore, and survive dangerous undertakings below.', Discern: 'Read a situation, uncover truths, and spot what matters.', Endure: 'Withstand pain, pressure, deprivation, and terrible conditions.', Evade: 'Avoid danger, escape pursuit, and stay out of harm’s way.', Hunt: 'Track people or beasts and understand how to bring them down.', Kill: 'Inflict harm with violence, weapons, or lethal intent.', Mend: 'Repair bodies, gear, supplies, and damaged situations.', Sneak: 'Hide, move unseen, steal, and act without drawing attention.' }
export const domainDetails: Record<string, string> = { Cursed: 'Ill-fated places, objects, and people changed by malign influence.', Desolate: 'Abandoned, empty, ruined, or inhospitable places.', Haven: 'Settlements, communities, and the people who live there.', Occult: 'Magic, impossible lore, and unnatural phenomena.', Religion: 'Faith, ritual, saints, gods, and their followers.', Technology: 'Machines, engineering, and the strange infrastructure below.', Warren: 'Tunnels, tight spaces, hidden routes, and subterranean life.', Wild: 'Beasts, wilderness, hunger, and nature without restraint.' }
export const skills = Object.keys(skillDetails)
export const domains = Object.keys(domainDetails)
